---
- name: Remove user and uninstall packages
  hosts: server
  become: true

  tasks:
    - name: Stop and disable NGINX service
      service:
        name: nginx
        state: stopped
        enabled: no

    - name: Uninstall packages (NGINX, git, zip)
      apt:
        name:
          - nginx
          - git
          - zip
        state: absent

    - name: Remove user hillel
      user:
        name: hillel
        state: absent
